// <auto-generated />
namespace CoachingCenterManagement.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Students2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Students2));
        
        string IMigrationMetadata.Id
        {
            get { return "202008080741147_Students2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
